package com.resumeanalyzer.web.dto;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Response DTO for resume analysis results.
 * Contains the complete analysis output including match percentage,
 * matched/missing skills, suggestions (both rule-based and AI-enhanced), and the full report.
 */
@Schema(
    name = "ResumeAnalysisResponse",
    description = "Complete analysis results for a resume matched against a job description"
)
public class ResumeAnalysisResponse {
    @Schema(
        description = "Overall match percentage between resume skills and job requirements",
        example = "75.5",
        minimum = "0",
        maximum = "100"
    )
    private double matchPercentage;

    @Schema(
        description = "Set of skills found in both resume and job description",
        example = "[\"Java\", \"Spring Boot\", \"SQL\"]"
    )
    private Set<String> matchedSkills;

    @Schema(
        description = "Set of skills required by job but missing from resume",
        example = "[\"Docker\", \"Kubernetes\", \"AWS\"]"
    )
    private Set<String> missingSkills;

    @Schema(
        description = "Rule-based improvement suggestions generated by the analyzer",
        example = "[\"Consider adding Docker to your skillset\", \"Highlight more database experience\"]"
    )
    private List<String> suggestions;

    @Schema(
        description = "AI-enhanced suggestions generated by Google Gemini API",
        example = "[\"Consider getting AWS certification\", \"Add cloud deployment experience\"]"
    )
    private List<String> aiSuggestions;

    @Schema(
        description = "Formatted text report with detailed analysis and recommendations"
    )
    private String report;

    public ResumeAnalysisResponse() {
    }

    public ResumeAnalysisResponse(double matchPercentage, Set<String> matchedSkills,
                                  Set<String> missingSkills, List<String> suggestions, String report) {
        this.matchPercentage = matchPercentage;
        this.matchedSkills = matchedSkills;
        this.missingSkills = missingSkills;
        this.suggestions = suggestions;
        this.aiSuggestions = new ArrayList<>();
        this.report = report;
    }

    public ResumeAnalysisResponse(double matchPercentage, Set<String> matchedSkills,
                                  Set<String> missingSkills, List<String> suggestions, 
                                  List<String> aiSuggestions, String report) {
        this.matchPercentage = matchPercentage;
        this.matchedSkills = matchedSkills;
        this.missingSkills = missingSkills;
        this.suggestions = suggestions;
        this.aiSuggestions = aiSuggestions;
        this.report = report;
    }

    public double getMatchPercentage() {
        return matchPercentage;
    }

    public void setMatchPercentage(double matchPercentage) {
        this.matchPercentage = matchPercentage;
    }

    public Set<String> getMatchedSkills() {
        return matchedSkills;
    }

    public void setMatchedSkills(Set<String> matchedSkills) {
        this.matchedSkills = matchedSkills;
    }

    public Set<String> getMissingSkills() {
        return missingSkills;
    }

    public void setMissingSkills(Set<String> missingSkills) {
        this.missingSkills = missingSkills;
    }

    public List<String> getSuggestions() {
        return suggestions;
    }

    public void setSuggestions(List<String> suggestions) {
        this.suggestions = suggestions;
    }

    public List<String> getAiSuggestions() {
        return aiSuggestions;
    }

    public void setAiSuggestions(List<String> aiSuggestions) {
        this.aiSuggestions = aiSuggestions;
    }

    public String getReport() {
        return report;
    }

    public void setReport(String report) {
        this.report = report;
    }
}